2020-08-16 16:55:14,573 - sever.flask_backend - ERROR - Exception on /livemonitor/ [GET]
Traceback (most recent call last):
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/junqingyang/My_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/junqingyang/Desktop/junqing_yang/sever/flask_backend.py", line 24, in getTop5
    "not": [null]
NameError: name 'null' is not defined
